_target_: train.train.ModelTrainer
weight_model: ${model}
matching_model:
  _target_: model.MaximumNumberConstraint
  annotator_num: ${annotator_num}
loss:
  _target_: train.loss.LossConfusion
  alpha: 0.01
  beta : 1
seed: 10
output_dir: ./outputs/${commit_hash}/${dataset.name}/$loss/${trainer.seed}
learning_rate: 0.005
weight_decay: 0.005
mode: train
dataset_name: ${dataset.name}
