train_dataset:
  _target_: dataset.spiral.SpiralDifferentNDatasetClassification
  seed : ${trainer.seed}
  batch_size: 1024
  mode : train
  system_num: 4

valid_dataset:
  _target_: dataset.spiral.SpiralDifferentNDatasetClassification
  seed : ${trainer.seed}
  batch_size: 1024
  mode : valid
  system_num: 4

test_dataset:
  _target_: dataset.spiral.SpiralDifferentNDatasetClassification
  seed : ${trainer.seed}
  batch_size: 1024
  mode : test
  system_num: 4

