name: spiral
sampling_rate: 1.0
model_name: xxx
target: dataset.SpiralDataset
filter_ratio: 0.0

train_dataset:
  _target_ : ${dataset.target}
  seed : ${trainer.seed}
  batch_size: 1024
  mode : train
  system_num: 3
  sampling_rate: ${dataset.sampling_rate}
  filter_ratio: ${dataset.filter_ratio}
  preprocess:
    _target_: preprocess.SpiralAreaPreprocessTaskAssignment
    debug: false

valid_dataset:
  _target_ : ${dataset.target}
  seed : ${trainer.seed}
  batch_size: 1024
  mode : valid
  system_num: 3
  preprocess:
    _target_: preprocess.SpiralAreaPreprocessTaskAssignment
    debug: false

test_dataset:
  _target_ : ${dataset.target}
  seed : ${trainer.seed}
  batch_size: 1024
  mode : test
  system_num: 3
  preprocess:
    _target_: preprocess.SpiralAreaPreprocessTaskAssignment
    debug: false
